### PR TITLE
movie: Mission to Mars (2000) initial review

### PR DESCRIPTION
**Pull request by paul-sheridan**
Super cheesy. Rating 2/5.

Note: I elaborated on the **human vs. inexplicable adversity** motivation.

### CODE REVIEW

**Review by odinlake — COMMENTED** [review]
I commented on this in a previous pull request that I think was closed...

**Comment by paul-sheridan** [comment]
Indeed. That was an abortive pull request. Git troubles... I saw your comment was about the **human vs. inexplicable adversity** motivation. It's updated in this pull request. How's it look to ya now?

**Comment by odinlake** [comment]
The present theme is defined in terms of facing "inexplicable problematic happenings" of which I see no evidence in the motivation. If there was nothing of that sort then maybe it'd be better to define a new theme that is explicitly about "humans try to solve a non-threatening enigmatic mystery".

**Comment by paul-sheridan** [comment]
I think the original **human vs. inexplicable adversity** could be justified because the humanoid head was somehow causing menacing, tornado-spawning dust storms, but to play it safe I just took it out.

**Pull request merged**
